<?php //print_r($this->layout()->portal['config_formulario']) ?>
<?php if( !empty($this->layout()->portal['config_formulario']) ) : ?>
<form data-form="form-dinamico" class="form-ingreso">
    <div class="caja-inputs">
        <?php foreach($this->layout()->portal['config_formulario'] as $form) : ?>
        <?php if($form['elemento'] == 'input') : ?>
            <div class="form-controls">
                <input type="text" name="<?php echo $form['keyinput']; ?>" id="<?php echo $form['keyinput'] ?>" class="campos-contacto-datos" placeholder="<?php echo $this->layout()->language->translate($form['nombre'].'*')['text']; ?>" <?php if( (int)$form['requerido'] ){ echo 'required=""'; } ?>>
                <div class="msgError"></div>
            </div>
        <?php elseif($form['elemento'] == 'select') : ?>
            <div class="form-controls">
                <select name="<?php echo $form['keyinput']; ?>" id="<?php echo $form['keyinput'] ?>" class="grayout select-filtro" placeholder="<?php echo $this->layout()->language->translate($form['nombre'].'*')['text']; ?>" <?php if( (int)$form['requerido'] ){ echo 'required=""'; } ?>>
                    <option value=""><?php echo $this->layout()->language->translate($form['nombre'].'*')['text']; ?></option>
                    <?php if(!empty($form['opcion'])) : foreach($form['opcion'] as $item) : ?>
                    <option value="<?php echo $item; ?>"><?php echo $item; ?></option>
                    <?php endforeach; endif; ?>
                </select>
                <div class="msgError"></div>
            </div>
        <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <!-- <div class="caja-inputs-3">
        <div class="escribe">
            <p>Precio S/:</p>
        </div>
        <div class="escribe-2">
            <input type="number" name="valorinicial" class="campos-dat" placeholder="Desde" min="0" required />
        </div>
        <span>- </span>

        <div class="escribe-2">
            <input type="number" name="valorfinal" class="campos-dat" placeholder="Hasta " min="0" required />
        </div>
    </div> -->
    <div class="caja-inputs-send">
        <input type="submit" name="button" id="button" value="BUSCAR" class="send-registro-recepcion" />
        <input type="hidden" name="proceso" id="proceso" />
    </div>
</form>
<?php endif; ?>

<script>
    <?php $this->inlineScript()->captureStart(); ?>
    
    $("[data-form='form-dinamico']").validate({
        ignore: [],
        rules: {
            dni: {
                required: true,
                number: true
            }
        },
        errorPlacement: function (error, element) {
            element.parents(".form-controls").find(".msgError").html(error);
        },
        submitHandler: function(form) {
            $.post("/login", $(form).serialize(), function(response){
                console.log(response);
                if(response.result === 'success') {
                    
                }
            }, 'json');
        }
    });

    <?php $this->inlineScript()->captureEnd(); ?>
</script>