<?php $this->headTitle('PRODUCTOS - '.mb_strtoupper($this->empresa['nombre']).' - FERIA VIRTUAL '.mb_strtoupper($this->layout()->feria['nombre'])); ?>

<?php
    if( isset($this->seo) ) {
        echo $this->headMeta()->appendName('keywords', $this->seo['keywords'])->setAutoEscape(false);
        echo $this->headMeta()->appendName('description', $this->seo['descripcion'])->setAutoEscape(false); 
    }
?>

<style>
@media screen and (max-width: 580px) {
    .info-modulo{
        display:none;
    }
}
</style>

<script src="js/jssor.slider-28.1.0.min.js" type="text/javascript"></script>
<script type="text/javascript">
    window.jssor_1_slider_init = function() {

    var jssor_1_SlideshowTransitions = [
    {$Duration:800,x:0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:-0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:-0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,y:0.3,$During:{$Top:[0.3,0.7]},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,y:-0.3,$SlideOut:true,$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,y:-0.3,$During:{$Top:[0.3,0.7]},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,y:0.3,$SlideOut:true,$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:0.3,$Cols:2,$During:{$Left:[0.3,0.7]},$ChessMode:{$Column:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:0.3,$Cols:2,$SlideOut:true,$ChessMode:{$Column:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,y:0.3,$Rows:2,$During:{$Top:[0.3,0.7]},$ChessMode:{$Row:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,y:0.3,$Rows:2,$SlideOut:true,$ChessMode:{$Row:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,y:0.3,$Cols:2,$During:{$Top:[0.3,0.7]},$ChessMode:{$Column:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,y:-0.3,$Cols:2,$SlideOut:true,$ChessMode:{$Column:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:0.3,$Rows:2,$During:{$Left:[0.3,0.7]},$ChessMode:{$Row:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:-0.3,$Rows:2,$SlideOut:true,$ChessMode:{$Row:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:0.3,y:0.3,$Cols:2,$Rows:2,$During:{$Left:[0.3,0.7],$Top:[0.3,0.7]},$ChessMode:{$Column:3,$Row:12},$Easing:{$Left:$Jease$.$InCubic,$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,x:0.3,y:0.3,$Cols:2,$Rows:2,$During:{$Left:[0.3,0.7],$Top:[0.3,0.7]},$SlideOut:true,$ChessMode:{$Column:3,$Row:12},$Easing:{$Left:$Jease$.$InCubic,$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,$Delay:20,$Clip:3,$Assembly:260,$Easing:{$Clip:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,$Delay:20,$Clip:3,$SlideOut:true,$Assembly:260,$Easing:{$Clip:$Jease$.$OutCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,$Delay:20,$Clip:12,$Assembly:260,$Easing:{$Clip:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
    {$Duration:800,$Delay:20,$Clip:12,$SlideOut:true,$Assembly:260,$Easing:{$Clip:$Jease$.$OutCubic,$Opacity:$Jease$.$Linear},$Opacity:2}
    ];

    var jssor_1_options = {
    $AutoPlay: 1,
    $SlideshowOptions: {
    $Class: $JssorSlideshowRunner$,
    $Transitions: jssor_1_SlideshowTransitions,
    $TransitionsOrder: 1
    },
    $ArrowNavigatorOptions: {
    $Class: $JssorArrowNavigator$
    },
    $ThumbnailNavigatorOptions: {
    $Class: $JssorThumbnailNavigator$,
    $SpacingX: 5,
    $SpacingY: 5
    }
    };

    var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

    /*#region responsive code begin*/

    var MAX_WIDTH = 820;

    function ScaleSlider() {
    var containerElement = jssor_1_slider.$Elmt.parentNode;
    var containerWidth = containerElement.clientWidth;

    if (containerWidth) {

        var expectedWidth = Math.min(MAX_WIDTH || containerWidth, containerWidth);

        jssor_1_slider.$ScaleWidth(expectedWidth);
    }
    else {
        window.setTimeout(ScaleSlider, 30);
    }
    }

    ScaleSlider();

    $Jssor$.$AddEvent(window, "load", ScaleSlider);
    $Jssor$.$AddEvent(window, "resize", ScaleSlider);
    $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
    /*#endregion responsive code end*/
    };
</script>

<?php
    echo $this->partial('partial/menus/encabezado-flechas', [
        'zona'=> $this->zona,
        'ordenzona'=> $this->ordenzona,
        'zonaEmpresaAnterior'=> $this->zonaEmpresaAnterior,
        'zonaEmpresaSiguiente'=> $this->zonaEmpresaSiguiente,
        'totalZonas'=> $this->totalZonas,
        'accion'=> 'productos'
    ]);
?>

<div class="wsp-all" style="display:none;">
    <a href="#"><img src="imagenes/whatsapp.svg"></a>
</div>

<?php
    $data = ['empresa'=> $this->empresa, 'zona'=> $this->zona];
    echo $this->partial('partial/empresa/header-logo-movil', $data);
?>

<?php
    $data = ['expositor'=> $this->expositor, 'empresa'=> $this->empresa, 'zona'=> $this->zona];
    echo $this->partial('partial/empresa/info-modulo', $data);
?>

<?php foreach($this->productos as $item) : ?>
<div class="info-proyectos">
    <div class="center">
        <div class="box-galeria">
            <div class="contai-proy">
                <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 980px; height: 520px; overflow: hidden; visibility: hidden;">
                    <!-- Loading Screen -->
                    <div data-u="loading" class="jssorl-009-spin" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; text-align: center; background-color: rgba(0, 0, 0, 0.7);">
                        <img style="margin-top: -19px; position: relative; top: 50%; width: 38px; height: 38px;" src="imagenes/spin.svg" />
                    </div>
                    <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 980px; height: 520px; overflow: hidden;">
                        <?php foreach( $item['imagenes'] as $imagen) : ?>
                        <div>
                            <img data-u="image" src="<?php echo $this->layout()->url_backend."/productos/slider/".$imagen['hash_imagen']; ?>" />
                            <div class="text-areacin"><?php echo $imagen['titulo']; ?></div>
                            <img data-u="thumb" src="<?php echo $this->layout()->url_backend."/productos/slider/".$imagen['hash_imagen']; ?>" />
                        </div>
                        <?php endforeach; ?>
                    </div>
                    <a data-scale="0" href="https://www.jssor.com" style="display: none; position: absolute;">web animation</a>
                    <!-- Thumbnail Navigator -->
                    <div data-u="thumbnavigator" class="jssort101" style="position: absolute; left: 0px; bottom: 0px; width: 0px; height: 0px; background-color: #fff;" data-autocenter="1" data-scale-bottom="0.75">
                        <div data-u="slides">
                            <div data-u="prototype" class="p" style="width: 190px; height: 90px;">
                                <div data-u="thumbnailtemplate" class="t"></div>
                                <svg viewbox="0 0 16000 16000" class="cv">
                                    <circle class="a" cx="8000" cy="8000" r="3238.1"></circle>
                                    <line class="a" x1="6190.5" y1="8000" x2="9809.5" y2="8000"></line>
                                    <line class="a" x1="8000" y1="9809.5" x2="8000" y2="6190.5"></line>
                                </svg>
                            </div>
                        </div>
                    </div>
                    <!-- Arrow Navigator -->
                    <div data-u="arrowleft" class="jssora106" style="width: 55px; height: 55px; top: 220px; left: 30px;" data-scale="0.75">
                        <svg viewbox="0 0 16000 16000" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
                            <circle class="c" cx="8000" cy="8000" r="6100.9"></circle>
                            <polyline class="a" points="7930.4,5495.7 5426.1,8000 7930.4,10504.3 "></polyline>
                        </svg>
                    </div>
                    <div data-u="arrowright" class="jssora106" style="width: 55px; height: 55px; top: 220px; right: 30px;" data-scale="0.75">
                        <svg viewbox="0 0 16000 16000" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
                            <circle class="c" cx="8000" cy="8000" r="6100.9"></circle>
                            <polyline class="a" points="8069.6,5495.7 10573.9,8000 8069.6,10504.3 "></polyline>
                        </svg>
                    </div>
                </div>
            </div>
            <div class="botones-proyectos">
                <div class="all-ds">
                    <div class="desde" style="width:150px">
                        <small><?php echo $this->layout()->language->translate('DESDE')['text']; ?></small>
                        <?php $simboloMonedas = ['S'=> 'PEN', 'D'=> 'USD']; ?>
                        <big><?php echo ( isset($simboloMonedas[$item['moneda']]) ? $simboloMonedas[$item['moneda']] : '' ); ?><?php echo number_format($item['precio_desde'], 0); ?></big>
                    </div>
                    <div class="taza">
                        <a href="<?php echo $this->layout()->idiomaSeleccionado; ?>/panel/planos/zona/<?php echo $this->ordenzona; ?>/empresa/<?php echo $this->ordenempresa; ?>"><?php echo $this->layout()->language->translate('RESÉRVALO HOY')['text']; ?></a>
                    </div>
                </div>
                <div class="menu-info">
                    <a href="javascript:void(0)" class="vr_open _recorrido360"><img src="imagenes/vr-cardboard.svg" width="25px" height="25px" />&nbsp;<?php echo $this->layout()->language->translate('RECORRIDO 360°')['text']; ?></a>
                    <a href="javascript:void(0)" class="map_open _mapa"><img src="imagenes/map.svg" width="25px" height="25px" />&nbsp;<?php echo $this->layout()->language->translate('MAPA')['text']; ?></a>
                    <a href="javascript:void(0)" class="pdf_open _brochure"><img src="imagenes/pdf.svg" width="25px" height="25px" />&nbsp;<?php echo $this->layout()->language->translate('BROCHURE')['text']; ?></a>
                    <a href="javascript:abrirVentanaWindow('<?php echo ( $item['enlace_wsp'] != '' ) ? $item['enlace_wsp'] : ''; ?>')" class="wsp-empresa _wsp"><img src="imagenes/wsp.svg" /></a>
                </div>
            </div>
        </div>
        <div class="space"></div>

        <div class="box-text">
            <div class="resume-proyecto">
                <div class="name-proyecto">
                    <h1><?php echo $item['nombre']; ?></h1>
                    <span></span> <small><i class="fas fa-map-marker-alt"></i> &nbsp;<?php echo $item['direccion']; ?></small>
                </div>
                <p><?php echo $this->layout()->language->translate($item['descripcion'])['text']; ?></p>
            </div>

            <div class="points-proyecto">
                <h1><?php echo $this->layout()->language->translate('INFORMACIÓN DEL PROYECTO')['text']; ?></h1>
                <div class="lista-1">
                    <?php $informacion = json_decode($item['informacion'], true); ?>
                    <?php if( $informacion ) : foreach($informacion as $info): ?>
                    <div class="desc"><small><?php echo $this->layout()->language->translate($info['titulo'])['text']; ?></small><span><?php echo $this->layout()->language->translate($info['descripcion'])['text']; ?></span></div>
                    <?php endforeach; endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="vr" class="well">
    <div class="modal-contents-2">
        <iframe class="paniframe" src="<?php echo $item['enlace_recorrido_virtual']; ?>" frameborder="o" scrolling="no" height="100%" width="100%" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
    </div>
</div>

<div id="pdf" class="well">
    <div class="modal-contents-2">
    <?php if( $item['tipo_enlace'] == 'PDF' ) : ?>
    <iframe class="paniframe" src="<?php echo $this->layout()->url_backend; ?>/productos/documentos/<?php echo $item['hash_pdf']; ?>" frameborder="o" scrolling="no" height="100%" width="100%" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
    <?php endif; ?>
    <?php if( $item['tipo_enlace'] == 'URL' ) : ?>
    <iframe class="paniframe" src="<?php echo $item['enlace']; ?>" frameborder="o" scrolling="no" height="100%" width="100%" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
    <?php endif; ?>
    </div>
</div>

<div id="map" class="well">
    <div class="modal-contents-2">
    <iframe src="<?php echo $item['enlace_mapa']; ?>" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
</div>

<?php endforeach; ?>

<div class="franja-amarillo">
    <div class="responsive-franja"><?php echo $this->partial('partial/menus/pie-pagina', ['empresa'=> $this->empresa, 'zona'=> $this->zona, 'accion'=> 'productos', 'totalProductos'=> $this->totalProductos, 'totalPromociones'=> $this->totalPromociones, 'totalPlanos'=> $this->totalPlanos]); ?></div>
    <a class="space"></a>
    <?php
        echo $this->partial('partial/menus/pie-pagina-flechas', [
            'empresa'=> $this->empresa,
            'zona'=> $this->zona,
            'ordenempresa'=> $this->ordenempresa,
            'ordenzona'=> $this->ordenzona,
            'empresaAnterior'=> $this->empresaAnterior,
            'empresaSiguiente'=> $this->empresaSiguiente,
            'totalEmpresas'=> $this->totalEmpresas
        ]);
    ?>
</div>

<?php
    $dataPartial = [
        'empresas'=> $this->empresas,
        'ordenzona'=> $this->ordenzona
    ];
    echo $this->partial('partial/empresa/slider', $dataPartial);
?>

<div class="franja-azul-atajos" style="display: none;">
    <a href="#" class="begin"><i class="fas fa-chevron-left"></i></a>
    <a href="#" class="end"><i class="fas fa-chevron-right"></i></a>
</div>

<script type="text/javascript">

    <?php $this->inlineScript()->captureStart(); ?>

    //Capturar Orden Empresa
    UsuariosEventos.ordenzona = '<?php echo $this->ordenzona; ?>';
    UsuariosEventos.ordenempresa = '<?php echo $this->ordenempresa; ?>';

    $(document).on("ready", function () {

        $('#vr, #map, #pdf').popup({
            transition: 'all 0.3s',
            closebutton: true
        });

    });

    jssor_1_slider_init();

    <?php $this->inlineScript()->captureEnd(); ?>

</script>
