<style>
	.resp-iframe {
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		border: 0;
	}
	.resp-container {
		position: relative;
		overflow: hidden;
		padding-top: 56.25%;
	}
</style>

<section class="realidad-virtual">
    <div class="resp-container">
		<?php $linkRv = (isset($this->enlace_rv)) ? $this->enlace_rv : $this->layout()->feria['link_rv']; ?>
	    <iframe class="resp-iframe" src="<?php echo $linkRv; ?>" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
	</div>
</section>

