<section class="rueda-home" style="height: 100vh;">
    <div class="avion" style="display: none;"><img src="imagenes/zep.png" width="300" /></div>

    <div class="wsp-all">
        <a href="javascript:void(0)"><img src="imagenes/whatsapp.svg" /></a>
    </div>
    <section class="drawer" id="drawer-name" data-drawer-target>
        <div class="drawer__overlay" data-drawer-close tabindex="1"></div>

        <div class="drawer__wrapper">
            <button class="drawer__close" data-drawer-close aria-label="Close Drawer"></button>
            <div class="drawer__content">
                <ul class="menu-responsive">
                    <a href="hall-planos-1.html">INICIAR FERIA</a>
                    <a href="hall.html"><img src="imagenes/iconos-menu-01.svg" />Recepción</a>
                    <a href="hall-planos-1.html"><img src="imagenes/iconos-menu-02.svg" />Expoferia</a>
                    <a href="conferencias.html"><img src="imagenes/iconos-menu-03.svg" />Conferencias</a>
                    <a href="auditorio-premium.html"><img src="imagenes/iconos-menu-03.svg" />Rueda de Negocios</a>
                </ul>
                <div class="logo-responsive-ccl"></div>
            </div>
        </div>
    </section>

    <div class="slide active">
        <a href="javascript:void(0)" class="boton-rueda">INGRESAR A RUEDA DE NEGOCIOS</a>
    </div>
</section>