<div class="banner-ad" style="padding-bottom: 2%;">
    <div class="banner-ad-center">
        <a href="javascript:void(0)">
            <img src="<?php echo (!isset($this->banner['banner-central-horizontal']['banner_programado'])) ? $this->layout()->url_backend.'/portal/banner/'.$this->banner['banner-central-horizontal']['banner_principal']['hash_banner'] : $this->layout()->url_backend.'/banner/imagenes/'.$this->banner['banner-central-horizontal']['banner_programado']['hash_banner']; ?>" alt="">
        </a>
    </div>
</div>