<div class="los-titulos">
    <h1><?php echo $this->titulo; ?></h1>
</div>

<div class="back-green" style="background-color: transparent;">
    <h2 style="display: none;">VER PROYECTOS SIMILARES</h2>

    <div class="center">
        <section class="bannersi" style="display: flex; align-items: center; justify-content: center;">
            <?php echo $this->partial('partial/principal/proyectos/busqueda-proyectos-banner-movil', [
                'proyectos'=> $this->proyectos
            ]); ?>
        </section>
    </div>
</div>

<div class="grid-go">
    <div class="grid-center">
        <div id="grid">
        <?php foreach($this->proyectos as $proyecto) : ?>
            <div class="caja" <?php if( $proyecto['destacado'] == "1" && $proyecto['hash_super_oferta'] != '' ) { echo 'id="vibrar" data-aos="fade-in"'; } ?>>
                <?php if( $proyecto['destacado'] == "1" && $proyecto['hash_super_oferta'] != '' ) : ?>
                <small><img src="<?php echo $this->layout()->url_backend."/productos/imagen/".$proyecto['hash_super_oferta']; ?>" alt=""></small>
                <?php endif; ?>
                <div class="logos-top">
                    <span><?php echo mb_strtoupper($proyecto['distrito']); ?></span>
                    <img src="<?php echo ( $proyecto['empresa_logo'] != '' ) ? $this->layout()->url_backend."/empresas/logo/".$proyecto['empresa_logo'] : 'imagenes/logo-inmo.png'; ?>" alt="">
                </div>
                <div>
                    <div class="back-standi">
                        <div class="agent">
                            <h2><span></span>ASESOR EN LINEA</h2>
                            <div class="box-dat">
                                <div class="foto">
                                    <img src="<?php echo ( $proyecto['expositor_foto'] != '' ) ? $this->layout()->url_backend."/expositores/foto/".$proyecto['expositor_foto'] : "imagenes/girl-phone.jpg"; ?>" alt="">
                                </div>
                                <div class="botones">
                                    <a href="javascript:void(0)"><img src="imagenes/icons-call-agent-01.svg" alt=""></a>
                                    <a href="javascript:void(0)"><img src="imagenes/icons-call-agent-02.svg" alt=""></a>
                                    <a href="javascript:void(0)"><img src="imagenes/icons-call-agent-03.svg" alt=""></a>
                                </div>
                            </div>
                        </div>
                        <div class="back">
                            <div class="logos-top-stand">
                                <div class="der">
                                    <img src="<?php echo ( isset($proyecto['stand_configuracion']['imagen_logo_1'])) ? $this->layout()->url_backend.'/paginas/stand-circular-portal/'.$proyecto['stand_configuracion']['imagen_logo_1']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular-portal/imagen_logo_1.svg'; ?>" alt="">
                                </div>
                                <div class="space-stand"></div>
                                <div class="right">
                                    <img src="<?php echo ( isset($proyecto['stand_configuracion']['imagen_logo_2'])) ? $this->layout()->url_backend.'/paginas/stand-circular-portal/'.$proyecto['stand_configuracion']['imagen_logo_2']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular-portal/imagen_logo_2.svg'; ?>" alt="">
                                </div>
                            </div>
                            <a href="<?php echo $this->layout()->idiomaSeleccionado; ?>/panel/proyecto/<?php echo $proyecto['hash_url']; ?>">
                                <div class="arte-stand-portal">
                                    <img src="<?php echo ( isset($proyecto['stand_configuracion']['imagen_banner_1'])) ? $this->layout()->url_backend.'/paginas/stand-circular-portal/'.$proyecto['stand_configuracion']['imagen_banner_1']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular-portal/imagen_banner_1.jpg'; ?>" alt="">
                                </div>
                            </a>
                            <div class="stand-portal">
                                <img src="imagenes/stand-portal.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="desc">
                    <div class="textos">
                        <big><?php echo mb_strtoupper($proyecto['nombre']); ?></big>
                        <span><?php echo mb_strtoupper($proyecto['titulo_recuadro']); ?></span>
                    </div>
                    <div class="textos-2">
                        <span>Precio desde</span>
                        <strong></strong>
                        <big><?php echo ( isset($this->layout()->simboloMoneda[$proyecto['moneda']]) ) ? $this->layout()->simboloMoneda[$proyecto['moneda']]." ".number_format($proyecto['precio_desde'], 2, ',', '') : number_format($proyecto['precio_desde'], 2, ',', ''); ?></big>
                    </div>
                    <div class="textos-3" style="<?php if( $proyecto['precio_especial'] !== '0.00' && $proyecto['sala_venta'] == "0") { echo "display: inherit;"; } ?>">
                        <span>Precio Especial</span>
                        <img src="imagenes/logo-lima.png" alt="">
                        <strong></strong>
                        <big><?php echo ( isset($this->layout()->simboloMoneda[$proyecto['moneda']]) ) ? $this->layout()->simboloMoneda[$proyecto['moneda']]." ".number_format($proyecto['precio_especial'], 2, '.', ',') : number_format($proyecto['precio_especial'], 2, '.', ','); ?></big>
                    </div>
                    <?php if( $proyecto['sala_venta'] == "1" && $proyecto['sala_venta_rv'] != "" ) : ?>
                    <a href="<?php echo $proyecto['sala_venta_rv']; ?>" class="textos-4">SALA DE VENTA VIRTUAL</a>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="space-grid-filtro"></div>
        <div class="banner-ad-go">
            <a href="javascript:void(0)">
                <img src="<?php echo (!isset($this->banner['banner-lateral-derecho-vertical']['banner_programado'])) ? $this->layout()->url_backend.'/portal/banner/'.$this->banner['banner-lateral-derecho-vertical']['banner_principal']['hash_banner'] : $this->layout()->url_backend.'/banner/imagenes/'.$this->banner['banner-lateral-derecho-vertical']['banner_programado']['hash_banner']; ?>" alt="">
            </a>
        </div>
    </div>
</div>