<style>
    .custom-tooltip {
        background: transparent;
        border: none;
        box-shadow: none;
    }

    .tooltip-card {
        width: 260px;
        background: #fff;
        border-radius: 12px;
        overflow: hidden;
        font-family: Arial;
    }

    .tooltip-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 8px 0;
        background: #f5f5f5;
        font-size: 12px;
        font-family: "Ubuntu", sans-serif;
    }

    .tooltip-header-title {
        background: #5c6bc0;
        color: #fff;
        padding: 4px 8px;
        border-radius: 0 7px 7px 0;
    }

    .tooltip-header-imagen {
        width: 45%;
    }

    .tooltip-body {
        padding: 10px 10px 5px 10px;
    }

    .tooltip-body h4 {
        margin: 0;
        font-size: 14px;
        font-family: "Ubuntu", sans-serif;
    }

    .tooltip-body p {
        margin: 4px 0;
        font-size: 12px;
        font-family: "Ubuntu", sans-serif;
    }

    .price {
        display: flex;
        justify-content: space-between;
        margin: 6px 0;
    }

    .price strong {
        color: red;
    }

    .btn {
        background: red;
        color: white;
        border: none;
        padding: 8px;
        border-radius: 20px;
        font-size: 12px;
        font-family: "Ubuntu", sans-serif;
        cursor: pointer;
        text-align: center;
    }

    .tooltip-body a {
        color: #fff;
        text-decoration: none;
    }

    .leaflet-popup-content {
        margin: 0;
    }
</style>

<div class="los-titulos">
    <h1>TODOS LOS PROYECTOS</h1>
</div>

<div class="filtro-todos">
    <button class="hide-counter" onclick="myFunction()">FILTROS</button>

    <form name="contacto" class="form-buscar" id="myDIVI">
        <span class="close2">X</span>

        <div class="all-selecters">
            <div class="citys">
                <h2>Tipos</h2>
                <select data-filtro="tipoHabitacion" class="grayout filtro-mapa select-filtro-mapa">
                    <option value="">Tipo</option>
                    <?php foreach($this->tipoHabitaciones as $item) : ?>
                    <option value="<?php echo $item['nombre']; ?>"><?php echo $item['nombre']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="space"></div>

            <div class="citys">
                <h2>Distrito</h2>
                <select data-filtro="distrito" class="grayout filtro-mapa select-filtro-mapa">
                    <option value="">Distrito</option>
                    <?php foreach($this->distritos as $item) : ?>
                    <option value="<?php echo $item['nombre']; ?>"><?php echo $item['nombre']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="space"></div>

            <div class="citys">
                <h2>N° de Habitaciones</h2>
                <select data-filtro="numeroHabitacion" class="grayout filtro-mapa select-filtro-mapa">
                    <option value="">Nro. de Habitaciones</option>
                    <?php foreach($this->numeroHabitaciones as $item) : ?>
                    <option value="<?php echo $item['nombre']; ?>"><?php echo $item['nombre']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="space"></div>
            <div class="citys">
                <h2>Precio S/</h2>
                <select data-filtro="rangoPrecios" class="grayout filtro-mapa select-filtro-mapa">
                    <option value="">Precio</option>
                    <?php foreach($this->rangoPrecios as $item) : ?>
                    <option value="<?php echo number_format($item['precio_min'], 2, ',', '') ." a ".number_format($item['precio_max'], 2, ',', ''); ?>"><?php echo number_format($item['precio_min'], 2, '.', ',') ." a ".number_format($item['precio_max'], 2, '.', ','); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="space"></div>

            <div class="citys">
                <h2>Etapa del Proyecto</h2>
                <select data-filtro="etapa" class="grayout filtro-mapa select-filtro-mapa">
                    <option value="">Etapa</option>
                    <?php foreach($this->etapas as $item) : ?>
                    <option value="<?php echo $item['nombre']; ?>"><?php echo $item['nombre']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="espacito"></div>

        <div class="boton">
            <input type="button" name="button" id="button" value="BUSCAR" onclick="App.mapManager.filterProjects(this)" class="send-filter" />
            <input type="hidden" name="proceso" id="proceso" />
        </div>
    </form>
</div>

<style>
    #map {
        height: 100%;
    }
    .content {
        width: 100%;
        height: 76vh;
    }
</style>

<div class="maps-filtro">
    <div class="center-mapa">
        <div class="content">
            <div id="map"></div>
        </div>
    </div>
</div>

<script>
    <?php $this->inlineScript()->captureStart(); ?>

    $(document).ready(function () {
        App.mapManager.init('map', {
            projects: JSON.parse('<?php echo $this->proyectosMapaGoogle; ?>'),
            urlBackend: '<?php echo $this->layout()->url_backend; ?>',
            selectedLanguage: '<?php echo $this->layout()->idiomaSeleccionado; ?>',
        });
    });

    <?php $this->inlineScript()->captureEnd(); ?>
</script>