<?php //print_r($this->layout()->portal) ?>

<?php $this->headTitle('FERIA VIRTUAL '.mb_strtoupper(@$this->layout()->feria['nombre'] ?? '')); ?>

<?php
    if( isset($this->seo) ) {
        echo $this->headMeta()->appendName('keywords', $this->seo['keywords'])->setAutoEscape(false);
        echo $this->headMeta()->appendName('description', $this->seo['descripcion'])->setAutoEscape(false); 
    }
?>

<?php echo $this->partial('partial/principal/css/formulario-principal', []); ?>

<section class="registro-home">
    <a class="show-hide" href="#" onclick="smooth()">VER REGISTRO</a>

    <div class="white-form-enter mt-1" id="show">
        <div class="blanco">
            <div class="fondo-logo-form">
                <img src="<?php echo ( $this->layout()->portal['hash_logo'] != '' ) ? $this->layout()->url_backend."/portal/imagenes/".$this->layout()->portal['hash_logo'] : 'imagenes/LOGO-EXPOHOGAR.svg'; ?>" alt="">
            </div>
            <div class="image-lap-responsive">
                <img src="<?php echo ( $this->layout()->portal['hash_logo_banner'] != '' ) ? $this->layout()->url_backend."/portal/imagenes/".$this->layout()->portal['hash_logo_banner'] : 'imagenes/lap-responsive.png'; ?>" alt="">
            </div>
            <h3><?php echo ( $this->layout()->portal['texto_titulo_formulario'] != '' ) ? $this->layout()->portal['texto_titulo_formulario'] : 'Descubre AQUÍ en las mejores ofertas, departamentos desde 0% de cuota inicial'; ?></h3>
            <?php echo $this->partial('partial/principal/formulario/formulario-principal', [
                'tipoHabitaciones'=> $this->tipoHabitaciones,
                'distritos'=> $this->distritos,
                'numeroHabitaciones'=> $this->numeroHabitaciones,
                'rangoPrecios'=> $this->rangoPrecios,
                'etapas'=> $this->etapas,
            ]); ?>
        </div>
    </div>

    <div class="vid-slider">
        <h1>TUTORIAL</h1>
        <p>¿Cómo usar la Portal Expohogar Inmobiliaria?</p>
        <div class="vid item">
            <iframe width="180" height="110" src="<?php echo ( $this->layout()->portal['url_video_tutorial'] != '') ? $this->layout()->portal['url_video_tutorial']: 'https://www.youtube.com/embed/9xwazD5SyVg'; ?>" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen title="TUTORIAL"></iframe>
            <a href="#">VER AHORA</a>
        </div>
    </div>
    <div class="video-popup">
        <div class="iframe-wrapper">
            <iframe width="820" height="500" src="" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen title="TUTORIAL"></iframe>
            <span class="close-video"></span>
        </div>
    </div>

    <div class="slide active" style="<?php echo (!isset($this->banner['banner-registro']['banner_programado'])) ? 'background: url('.$this->layout()->url_backend.'/portal/banner/'.$this->banner['banner-registro']['banner_principal']['hash_banner'].') no-repeat fixed center' : 'background: url('.$this->layout()->url_backend.'/banner/imagenes/'.$this->banner['banner-registro']['banner_programado']['hash_banner'].') no-repeat fixed center'; ?>"></div>

</section>

<?php echo $this->partial('partial/principal/banner/banner-principal', ['banner'=> $this->banner]); ?>

<?php 
    echo $this->partial(
        'partial/principal/proyectos/proyectos-destacados',
        [
            'proyectos'=> $this->proyectosMasDestacados,
            'titulo'=> 'INMUEBLES MÁS DESTACADOS'
        ]
    );
?>

<?php echo $this->partial('partial/principal/proyectos/proyectos-filtros', [
    'proyectosMasDestacados'=> $this->proyectosMasDestacados,
    'tipoHabitaciones'=> $this->tipoHabitaciones,
    'distritos'=> $this->distritos,
    'numeroHabitaciones'=> $this->numeroHabitaciones,
    'rangoPrecios'=> $this->rangoPrecios,
    'etapas'=> $this->etapas,
    'proyectosMapaGoogle'=> $this->proyectosMapaGoogle
]); ?>

<script>
    <?php $this->inlineScript()->captureStart(); ?>

    <?php $this->inlineScript()->captureEnd(); ?>
</script>