<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,200;0,400;0,600;0,700;0,900;1,200;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet" />
        <title>Feria Virtual</title>
        <style>
            body {
                font-family: Kanit, sans-serif;
            }
        </style>
    </head>
    <body>
        <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    <?php echo $this->contenidoCorreo; ?>
                </td>
            </tr>
			<tr>
                <td>
                    <div style="margin: 4px 0;">
                        <?php if( $this->informacion['hash_imagen'] != '' ) : ?>
                        <img src="<?php echo $this->layout()->url_backend."/productos/imagen/".$this->informacion['hash_imagen'] ?>" width="210">
                        <?php endif; ?>
                    </div>
                    <div style="margin: 4px 0;">
                        <?php if( $this->informacion['tipo_enlace'] == 'URL' && $this->informacion['enlace'] != '' ) : ?>
                        <a href="<?php echo $this->informacion['enlace']; ?>" style="font-size: 15px;"><?php echo $this->informacion['enlace']; ?></a>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
			<tr>
                <td>
                    <p style="margin: 4px 0;">
                        Atte.
                    </p>
                </td>
            </tr>
			<tr>
                <td>
                    <p style="margin: 4px 0;">
                        <?php echo mb_strtoupper($this->layout()->feria['nombre']); ?> <?php echo date('Y'); ?>
                    </p>
                </td>
            </tr>
        </table>
    </body>
</html>