<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,200;0,400;0,600;0,700;0,900;1,200;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet" />
        <title>Feria Virtual</title>
        <style>
            body {
                font-family: Kanit, sans-serif;
            }
        </style>
    </head>
    <body>
        <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    <?php echo $this->contenidoCorreo; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <p style="margin: 4px 0;">
                        <strong>DATOS DEL CLIENTE:</strong>
                    </p>
                </td>
            </tr>
			<tr>
                <td>
                    <p style="margin: 4px 0;">
                        <strong>Nombres: </strong> <?php echo $this->visitante['nombres']; ?><br>
                        <strong>Apellidos: </strong> <?php echo $this->visitante['apellido_paterno']." ".$this->visitante['apellido_materno']; ?><br>
                        <strong>Correo: </strong> <?php echo $this->visitante['correo'] ?><br>
                        <strong>Teléfono: </strong> <?php echo $this->visitante['telefono'] ?>
                    </p>
                </td>
            </tr>
			<tr>
                <td>
                    <p style="margin: 4px 0;">
                        Atte.
                    </p>
                </td>
            </tr>
			<tr>
                <td>
                    <p style="margin: 4px 0;">
                        <?php echo mb_strtoupper($this->layout()->feria['nombre']); ?> <?php echo date('Y'); ?>
                    </p>
                </td>
            </tr>
        </table>
    </body>
</html>